# Generated by Django 3.1.2 on 2020-10-11 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201010_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='time',
            field=models.CharField(default='None', max_length=300),
        ),
    ]
